version: 0.0
os: linux
files:
  - source: .
    destination: /home/ubuntu/47-fund-web-app
hooks:
  AfterInstall:
    - location: scripts/install_app_dependencies
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/redeploy_api
      timeout: 300
      runas: root
