INSERT INTO POSITIONS
    (
        CALDT,
        FUND,
        TICKER,
        ASSET_CLASS,
        SHARES,
        PRICE,
        FX_RATE
    )
SELECT
    CALDT,
    FUND,
    TICKER,
    ASSET_CLASS,
    SHARES,
    PRICE,
    FX_RATE
FROM "{{xf_table}}"
ON CONFLICT (CALDT, FUND, TICKER)
DO UPDATE SET
    CALDT = EXCLUDED.CALDT,
    FUND = EXCLUDED.FUND,
    TICKER = EXCLUDED.TICKER,
    ASSET_CLASS = EXCLUDED.ASSET_CLASS,
    SHARES = EXCLUDED.SHARES,
    PRICE = EXCLUDED.PRICE,
    FX_RATE = EXCLUDED.FX_RATE
;
