INSERT INTO TRADES
    (
        CALDT,
        FUND,
        TICKER,
        TRANSACTION_ID,
        ASSET_CLASS,
        SHARES_TRADED,
        PRICE_TRADED,
        BUY_SELL
    )
SELECT
    CALDT,
    FUND,
    TICKER,
    TRANSACTION_ID,
    ASSET_CLASS,
    SHARES_TRADED,
    PRICE_TRADED,
    BUY_SELL
FROM "{{xf_table}}"
ON CONFLICT (CALDT, FUND, TICKER, TRANSACTION_ID)
DO UPDATE SET
    CALDT = EXCLUDED.CALDT,
    FUND = EXCLUDED.FUND,
    TICKER = EXCLUDED.TICKER,
    TRANSACTION_ID = EXCLUDED.TRANSACTION_ID,
    ASSET_CLASS = EXCLUDED.ASSET_CLASS,
    SHARES_TRADED = EXCLUDED.SHARES_TRADED,
    PRICE_TRADED = EXCLUDED.PRICE_TRADED,
    BUY_SELL = EXCLUDED.BUY_SELL
;
