INSERT INTO DELTA_NAV
    (
        CALDT,
        FUND,
        STARTING_VALUE,
        ENDING_VALUE,
        DEPOSITS_WITHDRAWALS
    )
SELECT
    CALDT,
    FUND,
    STARTING_VALUE,
    ENDING_VALUE,
    DEPOSITS_WITHDRAWALS
FROM "{{xf_table}}"
ON CONFLICT (CALDT, FUND)
DO UPDATE SET
    CALDT = EXCLUDED.CALDT,
    FUND = EXCLUDED.FUND,
    STARTING_VALUE = EXCLUDED.STARTING_VALUE,
    ENDING_VALUE = EXCLUDED.ENDING_VALUE,
    DEPOSITS_WITHDRAWALS = EXCLUDED.DEPOSITS_WITHDRAWALS
;
