INSERT INTO DIVIDENDS
    (
        CALDT,
        FUND,
        TICKER,
        ACTION_ID,
        GROSS_RATE,
        GROSS_AMOUNT
    )
SELECT
    CALDT,
    FUND,
    TICKER,
    ACTION_ID,
    GROSS_RATE,
    GROSS_AMOUNT
FROM "{{xf_table}}"
ON CONFLICT (CALDT, FUND, TICKER, ACTION_ID)
DO UPDATE SET
    CALDT = EXCLUDED.CALDT,
    FUND = EXCLUDED.FUND,
    TICKER = EXCLUDED.TICKER,
    ACTION_ID = EXCLUDED.ACTION_ID,
    GROSS_RATE = EXCLUDED.GROSS_RATE,
    GROSS_AMOUNT = EXCLUDED.GROSS_AMOUNT
;
