INSERT INTO RISK_FREE_RATE
    (
        CALDT,
        YIELD,
        RETURN
    )
SELECT
    CALDT,
    YIELD,
    RETURN
FROM "{{xf_table}}"
ON CONFLICT (CALDT)
DO UPDATE SET
    CALDT = EXCLUDED.CALDT,
    YIELD = EXCLUDED.YIELD,
    RETURN = EXCLUDED.RETURN
;
