CREATE TABLE IF NOT EXISTS DIVIDENDS (
    CALDT DATE NOT NULL,
    FUND VARCHAR(255) NOT NULL,
    TICKER VARCHAR(255) NOT NULL,
    ACTION_ID VARCHAR(255) NOT NULL,
    GROSS_RATE NUMERIC(18,6) NOT NULL,
    GROSS_AMOUNT NUMERIC(18,6) NOT NULL,
    CONSTRAINT UNIQUE_DIVIDEND UNIQUE (CALDT, FUND, TICKER, ACTION_ID)
);
