INSERT INTO delta_nav
    (
    date,
    fund,
    "AccountAlias",
    "Model",
    "CurrencyPrimary",
    "FromDate",
    "ToDate",
    "StartingValue",
    "Mtm",
    "MtmAtPaxos",
    "Realized",
    "ChangeInUnrealized",
    "CostAdjustments",
    "TransferredPnlAdjustments",
    "DepositsWithdrawals",
    "CarbonCredits",
    "Donations",
    "InternalCashTransfers",
    "PaxosTransfers",
    "ExcessFundSweep",
    "AssetTransfers",
    "DebitCardActivity",
    "BillPay",
    "GrantActivity",
    "Dividends",
    "WithholdingTax",
    "871mWithholding",
    "WithholdingTaxCollected",
    "ChangeInDividendAccruals",
    "Interest",
    "ChangeInInterestAccruals",
    "BrokerFees",
    "changeInBrokerFeeAccruals",
    "AdvisorFees",
    "ClientFees",
    "OtherFees",
    "FeesReceivables",
    "Commissions",
    "CommissionsAtPaxos",
    "ReferralFee",
    "CommissionCreditsRedemption",
    "CommissionReceivables",
    "ForexCommissions",
    "TransactionTax",
    "TaxReceivables",
    "SalesTax",
    "BillableSalesTax",
    "SoftDollars",
    "NetFxTrading",
    "FxTranslation",
    "LinkingAdjustments",
    "ClientAccountID",
    "EndingValue",
    "TWR",
    "CorporateActionProceeds",
    "ChangeInIncentiveCouponAccruals",
    "OtherIncome",
    "Other"
    )
SELECT
    date,
    fund,
    "AccountAlias",
    "Model",
    "CurrencyPrimary",
    "FromDate",
    "ToDate",
    "StartingValue",
    "Mtm",
    "MtmAtPaxos",
    "Realized",
    "ChangeInUnrealized",
    "CostAdjustments",
    "TransferredPnlAdjustments",
    "DepositsWithdrawals",
    "CarbonCredits",
    "Donations",
    "InternalCashTransfers",
    "PaxosTransfers",
    "ExcessFundSweep",
    "AssetTransfers",
    "DebitCardActivity",
    "BillPay",
    "GrantActivity",
    "Dividends",
    "WithholdingTax",
    "871mWithholding",
    "WithholdingTaxCollected",
    "ChangeInDividendAccruals",
    "Interest",
    "ChangeInInterestAccruals",
    "BrokerFees",
    "changeInBrokerFeeAccruals",
    "AdvisorFees",
    "ClientFees",
    "OtherFees",
    "FeesReceivables",
    "Commissions",
    "CommissionsAtPaxos",
    "ReferralFee",
    "CommissionCreditsRedemption",
    "CommissionReceivables",
    "ForexCommissions",
    "TransactionTax",
    "TaxReceivables",
    "SalesTax",
    "BillableSalesTax",
    "SoftDollars",
    "NetFxTrading",
    "FxTranslation",
    "LinkingAdjustments",
    "ClientAccountID",
    "EndingValue",
    "TWR",
    "CorporateActionProceeds",
    "ChangeInIncentiveCouponAccruals",
    "OtherIncome",
    "Other"
FROM "{{stage_table}}"
ON CONFLICT (date, fund)
DO UPDATE SET
    "AccountAlias" = EXCLUDED."AccountAlias",
    "Model" = EXCLUDED."Model",
    "CurrencyPrimary" = EXCLUDED."CurrencyPrimary",
    "FromDate" = EXCLUDED."FromDate",
    "ToDate" = EXCLUDED."ToDate",
    "StartingValue" = EXCLUDED."StartingValue",
    "Mtm" = EXCLUDED."Mtm",
    "MtmAtPaxos" = EXCLUDED."MtmAtPaxos",
    "Realized" = EXCLUDED."Realized",
    "ChangeInUnrealized" = EXCLUDED."ChangeInUnrealized",
    "CostAdjustments" = EXCLUDED."CostAdjustments",
    "TransferredPnlAdjustments" = EXCLUDED."TransferredPnlAdjustments",
    "DepositsWithdrawals" = EXCLUDED."DepositsWithdrawals",
    "CarbonCredits" = EXCLUDED."CarbonCredits",
    "Donations" = EXCLUDED."Donations",
    "InternalCashTransfers" = EXCLUDED."InternalCashTransfers",
    "PaxosTransfers" = EXCLUDED."PaxosTransfers",
    "ExcessFundSweep" = EXCLUDED."ExcessFundSweep",
    "AssetTransfers" = EXCLUDED."AssetTransfers",
    "DebitCardActivity" = EXCLUDED."DebitCardActivity",
    "BillPay" = EXCLUDED."BillPay",
    "GrantActivity" = EXCLUDED."GrantActivity",
    "Dividends" = EXCLUDED."Dividends",
    "WithholdingTax" = EXCLUDED."WithholdingTax",
    "871mWithholding" = EXCLUDED."871mWithholding",
    "WithholdingTaxCollected" = EXCLUDED."WithholdingTaxCollected",
    "ChangeInDividendAccruals" = EXCLUDED."ChangeInDividendAccruals",
    "Interest" = EXCLUDED."Interest",
    "ChangeInInterestAccruals" = EXCLUDED."ChangeInInterestAccruals",
    "BrokerFees" = EXCLUDED."BrokerFees",
    "changeInBrokerFeeAccruals" = EXCLUDED."changeInBrokerFeeAccruals",
    "AdvisorFees" = EXCLUDED."AdvisorFees",
    "ClientFees" = EXCLUDED."ClientFees",
    "OtherFees" = EXCLUDED."OtherFees",
    "FeesReceivables" = EXCLUDED."FeesReceivables",
    "Commissions" = EXCLUDED."Commissions",
    "CommissionsAtPaxos" = EXCLUDED."CommissionsAtPaxos",
    "ReferralFee" = EXCLUDED."ReferralFee",
    "CommissionCreditsRedemption" = EXCLUDED."CommissionCreditsRedemption",
    "CommissionReceivables" = EXCLUDED."CommissionReceivables",
    "ForexCommissions" = EXCLUDED."ForexCommissions",
    "TransactionTax" = EXCLUDED."TransactionTax",
    "TaxReceivables" = EXCLUDED."TaxReceivables",
    "SalesTax" = EXCLUDED."SalesTax",
    "BillableSalesTax" = EXCLUDED."BillableSalesTax",
    "SoftDollars" = EXCLUDED."SoftDollars",
    "NetFxTrading" = EXCLUDED."NetFxTrading",
    "FxTranslation" = EXCLUDED."FxTranslation",
    "LinkingAdjustments" = EXCLUDED."LinkingAdjustments",
    "ClientAccountID" = EXCLUDED."ClientAccountID",
    "EndingValue" = EXCLUDED."EndingValue",
    "TWR" = EXCLUDED."TWR",
    "CorporateActionProceeds" = EXCLUDED."CorporateActionProceeds",
    "ChangeInIncentiveCouponAccruals" = EXCLUDED."ChangeInIncentiveCouponAccruals",
    "OtherIncome" = EXCLUDED."OtherIncome",
    "Other" = EXCLUDED."Other"
;
