INSERT INTO dividends
    (
    date,
    fund,
    "AccountAlias",
    "Model",
    "CurrencyPrimary",
    "FXRateToBase",
    "AssetClass",
    "SubCategory",
    "Symbol",
    "Description",
    "Conid",
    "SecurityID",
    "SecurityIDType",
    "CUSIP",
    "ISIN",
    "FIGI",
    "ListingExchange",
    "UnderlyingConid",
    "UnderlyingSymbol",
    "UnderlyingSecurityID",
    "UnderlyingListingExchange",
    "Issuer",
    "IssuerCountryCode",
    "Multiplier",
    "Strike",
    "Expiry",
    "Put/Call",
    "PrincipalAdjustFactor",
    "ExDate",
    "PayDate",
    "Quantity",
    "Tax",
    "Fee",
    "GrossRate",
    "GrossAmount",
    "NetAmount",
    "Code",
    "FromAcct",
    "ToAcct",
    "ActionID",
    "SerialNumber",
    "DeliveryType",
    "ClientAccountID",
    "Fineness",
    "Weight",
    "ReportDate",
    "CommodityType"
    )
SELECT
    date,
    fund,
    "AccountAlias",
    "Model",
    "CurrencyPrimary",
    "FXRateToBase",
    "AssetClass",
    "SubCategory",
    "Symbol",
    "Description",
    "Conid",
    "SecurityID",
    "SecurityIDType",
    "CUSIP",
    "ISIN",
    "FIGI",
    "ListingExchange",
    "UnderlyingConid",
    "UnderlyingSymbol",
    "UnderlyingSecurityID",
    "UnderlyingListingExchange",
    "Issuer",
    "IssuerCountryCode",
    "Multiplier",
    "Strike",
    "Expiry",
    "Put/Call",
    "PrincipalAdjustFactor",
    "ExDate",
    "PayDate",
    "Quantity",
    "Tax",
    "Fee",
    "GrossRate",
    "GrossAmount",
    "NetAmount",
    "Code",
    "FromAcct",
    "ToAcct",
    "ActionID",
    "SerialNumber",
    "DeliveryType",
    "ClientAccountID",
    "Fineness",
    "Weight",
    "ReportDate",
    "CommodityType"
FROM "{{stage_table}}"
ON CONFLICT (date, fund, "Symbol")
DO UPDATE SET
    "AccountAlias" = EXCLUDED."AccountAlias",
    "Model" = EXCLUDED."Model",
    "CurrencyPrimary" = EXCLUDED."CurrencyPrimary",
    "FXRateToBase" = EXCLUDED."FXRateToBase",
    "AssetClass" = EXCLUDED."AssetClass",
    "SubCategory" = EXCLUDED."SubCategory",
    "Symbol" = EXCLUDED."Symbol",
    "Description" = EXCLUDED."Description",
    "Conid" = EXCLUDED."Conid",
    "SecurityID" = EXCLUDED."SecurityID",
    "SecurityIDType" = EXCLUDED."SecurityIDType",
    "CUSIP" = EXCLUDED."CUSIP",
    "ISIN" = EXCLUDED."ISIN",
    "FIGI" = EXCLUDED."FIGI",
    "ListingExchange" = EXCLUDED."ListingExchange",
    "UnderlyingConid" = EXCLUDED."UnderlyingConid",
    "UnderlyingSymbol" = EXCLUDED."UnderlyingSymbol",
    "UnderlyingSecurityID" = EXCLUDED."UnderlyingSecurityID",
    "UnderlyingListingExchange" = EXCLUDED."UnderlyingListingExchange",
    "Issuer" = EXCLUDED."Issuer",
    "IssuerCountryCode" = EXCLUDED."IssuerCountryCode",
    "Multiplier" = EXCLUDED."Multiplier",
    "Strike" = EXCLUDED."Strike",
    "Expiry" = EXCLUDED."Expiry",
    "Put/Call" = EXCLUDED."Put/Call",
    "PrincipalAdjustFactor" = EXCLUDED."PrincipalAdjustFactor",
    "ExDate" = EXCLUDED."ExDate",
    "PayDate" = EXCLUDED."PayDate",
    "Quantity" = EXCLUDED."Quantity",
    "Tax" = EXCLUDED."Tax",
    "Fee" = EXCLUDED."Fee",
    "GrossRate" = EXCLUDED."GrossRate",
    "GrossAmount" = EXCLUDED."GrossAmount",
    "NetAmount" = EXCLUDED."NetAmount",
    "Code" = EXCLUDED."Code",
    "FromAcct" = EXCLUDED."FromAcct",
    "ToAcct" = EXCLUDED."ToAcct",
    "ActionID" = EXCLUDED."ActionID",
    "SerialNumber" = EXCLUDED."SerialNumber",
    "DeliveryType" = EXCLUDED."DeliveryType",
    "ClientAccountID" = EXCLUDED."ClientAccountID",
    "Fineness" = EXCLUDED."Fineness",
    "Weight" = EXCLUDED."Weight",
    "ReportDate" = EXCLUDED."ReportDate",
    "CommodityType" = EXCLUDED."CommodityType"
;
