INSERT INTO nav
    (
    date,
    fund,
    "AccountAlias",
    "Model",
    "CurrencyPrimary",
    "ReportDate",
    "Cash",
    "CashLong",
    "CashShort",
    "BrokerCashComponent",
    "BrokerCashComponentLong",
    "BrokerCashComponentShort",
    "FDICInsuredBankSweepAccountCashComponent",
    "FDICInsuredBankSweepAccountCashComponentLong",
    "FDICInsuredBankSweepAccountCashComponentShort",
    "InsuredBankDepositRedemptionCashComponent",
    "InsuredBankDepositRedemptionCashComponentLong",
    "InsuredBankDepositRedemptionCashComponentShort",
    "SLBCashCollateral",
    "SLBCashCollateralLong",
    "SLBCashCollateralShort",
    "Stock",
    "StockLong",
    "StockShort",
    "IPOSubscription",
    "IPOSubscriptionLong",
    "IPOSubscriptionShort",
    "SLBDirectSecuritiesBorrowed",
    "SLBDirectSecuritiesBorrowedLong",
    "SLBDirectSecuritiesBorrowedShort",
    "SLBDirectSecuritiesLent",
    "SLBDirectSecuritiesLentLong",
    "SLBDirectSecuritiesLentShort",
    "Options",
    "OptionsLong",
    "OptionsShort",
    "Bonds",
    "BondsLong",
    "BondsShort",
    "Commodities",
    "CommoditiesLong",
    "CommoditiesShort",
    "Notes",
    "NotesLong",
    "NotesShort",
    "Funds",
    "FundsLong",
    "FundsShort",
    "DividendAccruals",
    "DividendAccrualsLong",
    "DividendAccrualsShort",
    "InterestAccruals",
    "InterestAccrualsLong",
    "InterestAccrualsShort",
    "BrokerInterestAccrualsComponent",
    "BrokerInterestAccrualsComponentLong",
    "BrokerInterestAccrualsComponentShort",
    "FDICInsuredAccountInterestAccrualsComponent",
    "FDICInsuredAccountInterestAccrualsComponentLong",
    "FDICInsuredAccountInterestAccrualsComponentShort",
    "BondInterestAccrualsComponent",
    "BondInterestAccrualsComponentLong",
    "BondInterestAccrualsComponentShort",
    "BrokerFeesAccrualsComponent",
    "BrokerFeesAccrualsComponentLong",
    "BrokerFeesAccrualsComponentShort",
    "EventContractInterestAccruals",
    "EventContractInterestAccrualsLong",
    "EventContractInterestAccrualsShort",
    "MarginFinancingChargeAccruals",
    "MarginFinancingChargeAccrualsLong",
    "MarginFinancingChargeAccrualsShort",
    "SoftDollars",
    "SoftDollarsLong",
    "SoftDollarsShort",
    "ForexCfdUnrealizedPl",
    "ForexCfdUnrealizedPlLong",
    "ForexCfdUnrealizedPlShort",
    "CfdUnrealizedPl",
    "CfdUnrealizedPlLong",
    "CfdUnrealizedPlShort",
    "PhysicalDelivery",
    "PhysicalDeliveryLong",
    "PhysicalDeliveryShort",
    "ClientAccountID",
    "Crypto",
    "CryptoLong",
    "CryptoShort",
    "Total",
    "TotalLong",
    "TotalShort",
    "IncentiveCouponAccruals",
    "IncentiveCouponAccrualsLong",
    "IncentiveCouponAccrualsShort"
    )
SELECT
    date,
    fund,
    "AccountAlias",
    "Model",
    "CurrencyPrimary",
    "ReportDate",
    "Cash",
    "CashLong",
    "CashShort",
    "BrokerCashComponent",
    "BrokerCashComponentLong",
    "BrokerCashComponentShort",
    "FDICInsuredBankSweepAccountCashComponent",
    "FDICInsuredBankSweepAccountCashComponentLong",
    "FDICInsuredBankSweepAccountCashComponentShort",
    "InsuredBankDepositRedemptionCashComponent",
    "InsuredBankDepositRedemptionCashComponentLong",
    "InsuredBankDepositRedemptionCashComponentShort",
    "SLBCashCollateral",
    "SLBCashCollateralLong",
    "SLBCashCollateralShort",
    "Stock",
    "StockLong",
    "StockShort",
    "IPOSubscription",
    "IPOSubscriptionLong",
    "IPOSubscriptionShort",
    "SLBDirectSecuritiesBorrowed",
    "SLBDirectSecuritiesBorrowedLong",
    "SLBDirectSecuritiesBorrowedShort",
    "SLBDirectSecuritiesLent",
    "SLBDirectSecuritiesLentLong",
    "SLBDirectSecuritiesLentShort",
    "Options",
    "OptionsLong",
    "OptionsShort",
    "Bonds",
    "BondsLong",
    "BondsShort",
    "Commodities",
    "CommoditiesLong",
    "CommoditiesShort",
    "Notes",
    "NotesLong",
    "NotesShort",
    "Funds",
    "FundsLong",
    "FundsShort",
    "DividendAccruals",
    "DividendAccrualsLong",
    "DividendAccrualsShort",
    "InterestAccruals",
    "InterestAccrualsLong",
    "InterestAccrualsShort",
    "BrokerInterestAccrualsComponent",
    "BrokerInterestAccrualsComponentLong",
    "BrokerInterestAccrualsComponentShort",
    "FDICInsuredAccountInterestAccrualsComponent",
    "FDICInsuredAccountInterestAccrualsComponentLong",
    "FDICInsuredAccountInterestAccrualsComponentShort",
    "BondInterestAccrualsComponent",
    "BondInterestAccrualsComponentLong",
    "BondInterestAccrualsComponentShort",
    "BrokerFeesAccrualsComponent",
    "BrokerFeesAccrualsComponentLong",
    "BrokerFeesAccrualsComponentShort",
    "EventContractInterestAccruals",
    "EventContractInterestAccrualsLong",
    "EventContractInterestAccrualsShort",
    "MarginFinancingChargeAccruals",
    "MarginFinancingChargeAccrualsLong",
    "MarginFinancingChargeAccrualsShort",
    "SoftDollars",
    "SoftDollarsLong",
    "SoftDollarsShort",
    "ForexCfdUnrealizedPl",
    "ForexCfdUnrealizedPlLong",
    "ForexCfdUnrealizedPlShort",
    "CfdUnrealizedPl",
    "CfdUnrealizedPlLong",
    "CfdUnrealizedPlShort",
    "PhysicalDelivery",
    "PhysicalDeliveryLong",
    "PhysicalDeliveryShort",
    "ClientAccountID",
    "Crypto",
    "CryptoLong",
    "CryptoShort",
    "Total",
    "TotalLong",
    "TotalShort",
    "IncentiveCouponAccruals",
    "IncentiveCouponAccrualsLong",
    "IncentiveCouponAccrualsShort"
FROM "{{stage_table}}"
ON CONFLICT (date, fund)
DO UPDATE SET
    "AccountAlias" = EXCLUDED."AccountAlias",
    "Model" = EXCLUDED."Model",
    "CurrencyPrimary" = EXCLUDED."CurrencyPrimary",
    "ReportDate" = EXCLUDED."ReportDate",
    "Cash" = EXCLUDED."Cash",
    "CashLong" = EXCLUDED."CashLong",
    "CashShort" = EXCLUDED."CashShort",
    "BrokerCashComponent" = EXCLUDED."BrokerCashComponent",
    "BrokerCashComponentLong" = EXCLUDED."BrokerCashComponentLong",
    "BrokerCashComponentShort" = EXCLUDED."BrokerCashComponentShort",
    "FDICInsuredBankSweepAccountCashComponent" = EXCLUDED."FDICInsuredBankSweepAccountCashComponent",
    "FDICInsuredBankSweepAccountCashComponentLong" = EXCLUDED."FDICInsuredBankSweepAccountCashComponentLong",
    "FDICInsuredBankSweepAccountCashComponentShort" = EXCLUDED."FDICInsuredBankSweepAccountCashComponentShort",
    "InsuredBankDepositRedemptionCashComponent" = EXCLUDED."InsuredBankDepositRedemptionCashComponent",
    "InsuredBankDepositRedemptionCashComponentLong" = EXCLUDED."InsuredBankDepositRedemptionCashComponentLong",
    "InsuredBankDepositRedemptionCashComponentShort" = EXCLUDED."InsuredBankDepositRedemptionCashComponentShort",
    "SLBCashCollateral" = EXCLUDED."SLBCashCollateral",
    "SLBCashCollateralLong" = EXCLUDED."SLBCashCollateralLong",
    "SLBCashCollateralShort" = EXCLUDED."SLBCashCollateralShort",
    "Stock" = EXCLUDED."Stock",
    "StockLong" = EXCLUDED."StockLong",
    "StockShort" = EXCLUDED."StockShort",
    "IPOSubscription" = EXCLUDED."IPOSubscription",
    "IPOSubscriptionLong" = EXCLUDED."IPOSubscriptionLong",
    "IPOSubscriptionShort" = EXCLUDED."IPOSubscriptionShort",
    "SLBDirectSecuritiesBorrowed" = EXCLUDED."SLBDirectSecuritiesBorrowed",
    "SLBDirectSecuritiesBorrowedLong" = EXCLUDED."SLBDirectSecuritiesBorrowedLong",
    "SLBDirectSecuritiesBorrowedShort" = EXCLUDED."SLBDirectSecuritiesBorrowedShort",
    "SLBDirectSecuritiesLent" = EXCLUDED."SLBDirectSecuritiesLent",
    "SLBDirectSecuritiesLentLong" = EXCLUDED."SLBDirectSecuritiesLentLong",
    "SLBDirectSecuritiesLentShort" = EXCLUDED."SLBDirectSecuritiesLentShort",
    "Options" = EXCLUDED."Options",
    "OptionsLong" = EXCLUDED."OptionsLong",
    "OptionsShort" = EXCLUDED."OptionsShort",
    "Bonds" = EXCLUDED."Bonds",
    "BondsLong" = EXCLUDED."BondsLong",
    "BondsShort" = EXCLUDED."BondsShort",
    "Commodities" = EXCLUDED."Commodities",
    "CommoditiesLong" = EXCLUDED."CommoditiesLong",
    "CommoditiesShort" = EXCLUDED."CommoditiesShort",
    "Notes" = EXCLUDED."Notes",
    "NotesLong" = EXCLUDED."NotesLong",
    "NotesShort" = EXCLUDED."NotesShort",
    "Funds" = EXCLUDED."Funds",
    "FundsLong" = EXCLUDED."FundsLong",
    "FundsShort" = EXCLUDED."FundsShort",
    "DividendAccruals" = EXCLUDED."DividendAccruals",
    "DividendAccrualsLong" = EXCLUDED."DividendAccrualsLong",
    "DividendAccrualsShort" = EXCLUDED."DividendAccrualsShort",
    "InterestAccruals" = EXCLUDED."InterestAccruals",
    "InterestAccrualsLong" = EXCLUDED."InterestAccrualsLong",
    "InterestAccrualsShort" = EXCLUDED."InterestAccrualsShort",
    "BrokerInterestAccrualsComponent" = EXCLUDED."BrokerInterestAccrualsComponent",
    "BrokerInterestAccrualsComponentLong" = EXCLUDED."BrokerInterestAccrualsComponentLong",
    "BrokerInterestAccrualsComponentShort" = EXCLUDED."BrokerInterestAccrualsComponentShort",
    "FDICInsuredAccountInterestAccrualsComponent" = EXCLUDED."FDICInsuredAccountInterestAccrualsComponent",
    "FDICInsuredAccountInterestAccrualsComponentLong" = EXCLUDED."FDICInsuredAccountInterestAccrualsComponentLong",
    "FDICInsuredAccountInterestAccrualsComponentShort" = EXCLUDED."FDICInsuredAccountInterestAccrualsComponentShort",
    "BondInterestAccrualsComponent" = EXCLUDED."BondInterestAccrualsComponent",
    "BondInterestAccrualsComponentLong" = EXCLUDED."BondInterestAccrualsComponentLong",
    "BondInterestAccrualsComponentShort" = EXCLUDED."BondInterestAccrualsComponentShort",
    "BrokerFeesAccrualsComponent" = EXCLUDED."BrokerFeesAccrualsComponent",
    "BrokerFeesAccrualsComponentLong" = EXCLUDED."BrokerFeesAccrualsComponentLong",
    "BrokerFeesAccrualsComponentShort" = EXCLUDED."BrokerFeesAccrualsComponentShort",
    "EventContractInterestAccruals" = EXCLUDED."EventContractInterestAccruals",
    "EventContractInterestAccrualsLong" = EXCLUDED."EventContractInterestAccrualsLong",
    "EventContractInterestAccrualsShort" = EXCLUDED."EventContractInterestAccrualsShort",
    "MarginFinancingChargeAccruals" = EXCLUDED."MarginFinancingChargeAccruals",
    "MarginFinancingChargeAccrualsLong" = EXCLUDED."MarginFinancingChargeAccrualsLong",
    "MarginFinancingChargeAccrualsShort" = EXCLUDED."MarginFinancingChargeAccrualsShort",
    "SoftDollars" = EXCLUDED."SoftDollars",
    "SoftDollarsLong" = EXCLUDED."SoftDollarsLong",
    "SoftDollarsShort" = EXCLUDED."SoftDollarsShort",
    "ForexCfdUnrealizedPl" = EXCLUDED."ForexCfdUnrealizedPl",
    "ForexCfdUnrealizedPlLong" = EXCLUDED."ForexCfdUnrealizedPlLong",
    "ForexCfdUnrealizedPlShort" = EXCLUDED."ForexCfdUnrealizedPlShort",
    "CfdUnrealizedPl" = EXCLUDED."CfdUnrealizedPl",
    "CfdUnrealizedPlLong" = EXCLUDED."CfdUnrealizedPlLong",
    "CfdUnrealizedPlShort" = EXCLUDED."CfdUnrealizedPlShort",
    "PhysicalDelivery" = EXCLUDED."PhysicalDelivery",
    "PhysicalDeliveryLong" = EXCLUDED."PhysicalDeliveryLong",
    "PhysicalDeliveryShort" = EXCLUDED."PhysicalDeliveryShort",
    "ClientAccountID" = EXCLUDED."ClientAccountID",
    "Crypto" = EXCLUDED."Crypto",
    "CryptoLong" = EXCLUDED."CryptoLong",
    "CryptoShort" = EXCLUDED."CryptoShort",
    "Total" = EXCLUDED."Total",
    "TotalLong" = EXCLUDED."TotalLong",
    "TotalShort" = EXCLUDED."TotalShort",
    "IncentiveCouponAccruals" = EXCLUDED."IncentiveCouponAccruals",
    "IncentiveCouponAccrualsLong" = EXCLUDED."IncentiveCouponAccrualsLong",
    "IncentiveCouponAccrualsShort" = EXCLUDED."IncentiveCouponAccrualsShort"
;
