INSERT INTO trades
    (
    date,
    fund,
    "AccountAlias",
    "Model",
    "CurrencyPrimary",
    "FXRateToBase",
    "AssetClass",
    "SubCategory",
    "Symbol",
    "Description",
    "Conid",
    "SecurityID",
    "SecurityIDType",
    "CUSIP",
    "ISIN",
    "FIGI",
    "ListingExchange",
    "UnderlyingConid",
    "UnderlyingSymbol",
    "UnderlyingSecurityID",
    "UnderlyingListingExchange",
    "Issuer",
    "IssuerCountryCode",
    "TradeID",
    "Multiplier",
    "RelatedTradeID",
    "Strike",
    "ReportDate",
    "Expiry",
    "DateTime",
    "Put/Call",
    "TradeDate",
    "PrincipalAdjustFactor",
    "SettleDateTarget",
    "TransactionType",
    "Exchange",
    "Quantity",
    "TradePrice",
    "TradeMoney",
    "Proceeds",
    "Taxes",
    "IBCommission",
    "IBCommissionCurrency",
    "NetCash",
    "ClosePrice",
    "Open/CloseIndicator",
    "Notes/Codes",
    "CostBasis",
    "FifoPnlRealized",
    "MtmPnl",
    "OrigTradePrice",
    "OrigTradeDate",
    "OrigTradeID",
    "OrigOrderID",
    "OrigTransactionID",
    "Buy/Sell",
    "ClearingFirmID",
    "IBOrderID",
    "TransactionID",
    "IBExecID",
    "RelatedTransactionID",
    "RTN",
    "BrokerageOrderID",
    "OrderReference",
    "VolatilityOrderLink",
    "ExchOrderID",
    "ExtExecID",
    "OrderTime",
    "OpenDateTime",
    "HoldingPeriodDateTime",
    "WhenRealized",
    "WhenReopened",
    "LevelOfDetail",
    "ChangeInPrice",
    "ChangeInQuantity",
    "OrderType",
    "ClientAccountID",
    "IsAPIOrder",
    "AccruedInterest",
    "InitialInvestment",
    "SerialNumber",
    "DeliveryType",
    "CommodityType",
    "Fineness",
    "Weight",
    "TraderID"
    )
SELECT
    date,
    fund,
    "AccountAlias",
    "Model",
    "CurrencyPrimary",
    "FXRateToBase",
    "AssetClass",
    "SubCategory",
    "Symbol",
    "Description",
    "Conid",
    "SecurityID",
    "SecurityIDType",
    "CUSIP",
    "ISIN",
    "FIGI",
    "ListingExchange",
    "UnderlyingConid",
    "UnderlyingSymbol",
    "UnderlyingSecurityID",
    "UnderlyingListingExchange",
    "Issuer",
    "IssuerCountryCode",
    "TradeID",
    "Multiplier",
    "RelatedTradeID",
    "Strike",
    "ReportDate",
    "Expiry",
    "DateTime",
    "Put/Call",
    "TradeDate",
    "PrincipalAdjustFactor",
    "SettleDateTarget",
    "TransactionType",
    "Exchange",
    "Quantity",
    "TradePrice",
    "TradeMoney",
    "Proceeds",
    "Taxes",
    "IBCommission",
    "IBCommissionCurrency",
    "NetCash",
    "ClosePrice",
    "Open/CloseIndicator",
    "Notes/Codes",
    "CostBasis",
    "FifoPnlRealized",
    "MtmPnl",
    "OrigTradePrice",
    "OrigTradeDate",
    "OrigTradeID",
    "OrigOrderID",
    "OrigTransactionID",
    "Buy/Sell",
    "ClearingFirmID",
    "IBOrderID",
    "TransactionID",
    "IBExecID",
    "RelatedTransactionID",
    "RTN",
    "BrokerageOrderID",
    "OrderReference",
    "VolatilityOrderLink",
    "ExchOrderID",
    "ExtExecID",
    "OrderTime",
    "OpenDateTime",
    "HoldingPeriodDateTime",
    "WhenRealized",
    "WhenReopened",
    "LevelOfDetail",
    "ChangeInPrice",
    "ChangeInQuantity",
    "OrderType",
    "ClientAccountID",
    "IsAPIOrder",
    "AccruedInterest",
    "InitialInvestment",
    "SerialNumber",
    "DeliveryType",
    "CommodityType",
    "Fineness",
    "Weight",
    "TraderID"
FROM "{{stage_table}}"
ON CONFLICT (date, fund, "Symbol")
DO UPDATE SET
    "AccountAlias" = EXCLUDED."AccountAlias",
    "Model" = EXCLUDED."Model",
    "CurrencyPrimary" = EXCLUDED."CurrencyPrimary",
    "FXRateToBase" = EXCLUDED."FXRateToBase",
    "AssetClass" = EXCLUDED."AssetClass",
    "SubCategory" = EXCLUDED."SubCategory",
    "Symbol" = EXCLUDED."Symbol",
    "Description" = EXCLUDED."Description",
    "Conid" = EXCLUDED."Conid",
    "SecurityID" = EXCLUDED."SecurityID",
    "SecurityIDType" = EXCLUDED."SecurityIDType",
    "CUSIP" = EXCLUDED."CUSIP",
    "ISIN" = EXCLUDED."ISIN",
    "FIGI" = EXCLUDED."FIGI",
    "ListingExchange" = EXCLUDED."ListingExchange",
    "UnderlyingConid" = EXCLUDED."UnderlyingConid",
    "UnderlyingSymbol" = EXCLUDED."UnderlyingSymbol",
    "UnderlyingSecurityID" = EXCLUDED."UnderlyingSecurityID",
    "UnderlyingListingExchange" = EXCLUDED."UnderlyingListingExchange",
    "Issuer" = EXCLUDED."Issuer",
    "IssuerCountryCode" = EXCLUDED."IssuerCountryCode",
    "TradeID" = EXCLUDED."TradeID",
    "Multiplier" = EXCLUDED."Multiplier",
    "RelatedTradeID" = EXCLUDED."RelatedTradeID",
    "Strike" = EXCLUDED."Strike",
    "ReportDate" = EXCLUDED."ReportDate",
    "Expiry" = EXCLUDED."Expiry",
    "DateTime" = EXCLUDED."DateTime",
    "Put/Call" = EXCLUDED."Put/Call",
    "TradeDate" = EXCLUDED."TradeDate",
    "PrincipalAdjustFactor" = EXCLUDED."PrincipalAdjustFactor",
    "SettleDateTarget" = EXCLUDED."SettleDateTarget",
    "TransactionType" = EXCLUDED."TransactionType",
    "Exchange" = EXCLUDED."Exchange",
    "Quantity" = EXCLUDED."Quantity",
    "TradePrice" = EXCLUDED."TradePrice",
    "TradeMoney" = EXCLUDED."TradeMoney",
    "Proceeds" = EXCLUDED."Proceeds",
    "Taxes" = EXCLUDED."Taxes",
    "IBCommission" = EXCLUDED."IBCommission",
    "IBCommissionCurrency" = EXCLUDED."IBCommissionCurrency",
    "NetCash" = EXCLUDED."NetCash",
    "ClosePrice" = EXCLUDED."ClosePrice",
    "Open/CloseIndicator" = EXCLUDED."Open/CloseIndicator",
    "Notes/Codes" = EXCLUDED."Notes/Codes",
    "CostBasis" = EXCLUDED."CostBasis",
    "FifoPnlRealized" = EXCLUDED."FifoPnlRealized",
    "MtmPnl" = EXCLUDED."MtmPnl",
    "OrigTradePrice" = EXCLUDED."OrigTradePrice",
    "OrigTradeDate" = EXCLUDED."OrigTradeDate",
    "OrigTradeID" = EXCLUDED."OrigTradeID",
    "OrigOrderID" = EXCLUDED."OrigOrderID",
    "OrigTransactionID" = EXCLUDED."OrigTransactionID",
    "Buy/Sell" = EXCLUDED."Buy/Sell",
    "ClearingFirmID" = EXCLUDED."ClearingFirmID",
    "IBOrderID" = EXCLUDED."IBOrderID",
    "TransactionID" = EXCLUDED."TransactionID",
    "IBExecID" = EXCLUDED."IBExecID",
    "RelatedTransactionID" = EXCLUDED."RelatedTransactionID",
    "RTN" = EXCLUDED."RTN",
    "BrokerageOrderID" = EXCLUDED."BrokerageOrderID",
    "OrderReference" = EXCLUDED."OrderReference",
    "VolatilityOrderLink" = EXCLUDED."VolatilityOrderLink",
    "ExchOrderID" = EXCLUDED."ExchOrderID",
    "ExtExecID" = EXCLUDED."ExtExecID",
    "OrderTime" = EXCLUDED."OrderTime",
    "OpenDateTime" = EXCLUDED."OpenDateTime",
    "HoldingPeriodDateTime" = EXCLUDED."HoldingPeriodDateTime",
    "WhenRealized" = EXCLUDED."WhenRealized",
    "WhenReopened" = EXCLUDED."WhenReopened",
    "LevelOfDetail" = EXCLUDED."LevelOfDetail",
    "ChangeInPrice" = EXCLUDED."ChangeInPrice",
    "ChangeInQuantity" = EXCLUDED."ChangeInQuantity",
    "OrderType" = EXCLUDED."OrderType",
    "ClientAccountID" = EXCLUDED."ClientAccountID",
    "IsAPIOrder" = EXCLUDED."IsAPIOrder",
    "AccruedInterest" = EXCLUDED."AccruedInterest",
    "InitialInvestment" = EXCLUDED."InitialInvestment",
    "SerialNumber" = EXCLUDED."SerialNumber",
    "DeliveryType" = EXCLUDED."DeliveryType",
    "CommodityType" = EXCLUDED."CommodityType",
    "Fineness" = EXCLUDED."Fineness",
    "Weight" = EXCLUDED."Weight",
    "TraderID" = EXCLUDED."TraderID"
;
