INSERT INTO positions
    (
    date,
    fund,
    "AccountAlias",
    "Model",
    "CurrencyPrimary",
    "FXRateToBase",
    "AssetClass",
    "SubCategory",
    "Symbol",
    "Description",
    "Conid",
    "SecurityID",
    "SecurityIDType",
    "CUSIP",
    "ISIN",
    "FIGI",
    "ListingExchange",
    "UnderlyingConid",
    "UnderlyingSymbol",
    "UnderlyingSecurityID",
    "UnderlyingListingExchange",
    "Issuer",
    "IssuerCountryCode",
    "Multiplier",
    "Strike",
    "Expiry",
    "Put/Call",
    "PrincipalAdjustFactor",
    "ReportDate",
    "Quantity",
    "MarkPrice",
    "PositionValue",
    "OpenPrice",
    "CostBasisPrice",
    "CostBasisMoney",
    "PercentOfNAV",
    "FifoPnlUnrealized",
    "Side",
    "LevelOfDetail",
    "OpenDateTime",
    "HoldingPeriodDateTime",
    "VestingDate",
    "Code",
    "OriginatingOrderID",
    "OriginatingTransactionID",
    "AccruedInterest",
    "ClientAccountID",
    "DeliveryType",
    "CommodityType",
    "Fineness",
    "Weight",
    "SerialNumber"
    )
SELECT
    date,
    fund,
    "AccountAlias",
    "Model",
    "CurrencyPrimary",
    "FXRateToBase",
    "AssetClass",
    "SubCategory",
    "Symbol",
    "Description",
    "Conid",
    "SecurityID",
    "SecurityIDType",
    "CUSIP",
    "ISIN",
    "FIGI",
    "ListingExchange",
    "UnderlyingConid",
    "UnderlyingSymbol",
    "UnderlyingSecurityID",
    "UnderlyingListingExchange",
    "Issuer",
    "IssuerCountryCode",
    "Multiplier",
    "Strike",
    "Expiry",
    "Put/Call",
    "PrincipalAdjustFactor",
    "ReportDate",
    "Quantity",
    "MarkPrice",
    "PositionValue",
    "OpenPrice",
    "CostBasisPrice",
    "CostBasisMoney",
    "PercentOfNAV",
    "FifoPnlUnrealized",
    "Side",
    "LevelOfDetail",
    "OpenDateTime",
    "HoldingPeriodDateTime",
    "VestingDate",
    "Code",
    "OriginatingOrderID",
    "OriginatingTransactionID",
    "AccruedInterest",
    "ClientAccountID",
    "DeliveryType",
    "CommodityType",
    "Fineness",
    "Weight",
    "SerialNumber"
FROM "{{stage_table}}"
ON CONFLICT (date, fund, "Symbol")
DO UPDATE SET
    "AccountAlias" = EXCLUDED."AccountAlias",
    "Model" = EXCLUDED."Model",
    "CurrencyPrimary" = EXCLUDED."CurrencyPrimary",
    "FXRateToBase" = EXCLUDED."FXRateToBase",
    "AssetClass" = EXCLUDED."AssetClass",
    "SubCategory" = EXCLUDED."SubCategory",
    "Symbol" = EXCLUDED."Symbol",
    "Description" = EXCLUDED."Description",
    "Conid" = EXCLUDED."Conid",
    "SecurityID" = EXCLUDED."SecurityID",
    "SecurityIDType" = EXCLUDED."SecurityIDType",
    "CUSIP" = EXCLUDED."CUSIP",
    "ISIN" = EXCLUDED."ISIN",
    "FIGI" = EXCLUDED."FIGI",
    "ListingExchange" = EXCLUDED."ListingExchange",
    "UnderlyingConid" = EXCLUDED."UnderlyingConid",
    "UnderlyingSymbol" = EXCLUDED."UnderlyingSymbol",
    "UnderlyingSecurityID" = EXCLUDED."UnderlyingSecurityID",
    "UnderlyingListingExchange" = EXCLUDED."UnderlyingListingExchange",
    "Issuer" = EXCLUDED."Issuer",
    "IssuerCountryCode" = EXCLUDED."IssuerCountryCode",
    "Multiplier" = EXCLUDED."Multiplier",
    "Strike" = EXCLUDED."Strike",
    "Expiry" = EXCLUDED."Expiry",
    "Put/Call" = EXCLUDED."Put/Call",
    "PrincipalAdjustFactor" = EXCLUDED."PrincipalAdjustFactor",
    "ReportDate" = EXCLUDED."ReportDate",
    "Quantity" = EXCLUDED."Quantity",
    "MarkPrice" = EXCLUDED."MarkPrice",
    "PositionValue" = EXCLUDED."PositionValue",
    "OpenPrice" = EXCLUDED."OpenPrice",
    "CostBasisPrice" = EXCLUDED."CostBasisPrice",
    "CostBasisMoney" = EXCLUDED."CostBasisMoney",
    "PercentOfNAV" = EXCLUDED."PercentOfNAV",
    "FifoPnlUnrealized" = EXCLUDED."FifoPnlUnrealized",
    "Side" = EXCLUDED."Side",
    "LevelOfDetail" = EXCLUDED."LevelOfDetail",
    "OpenDateTime" = EXCLUDED."OpenDateTime",
    "HoldingPeriodDateTime" = EXCLUDED."HoldingPeriodDateTime",
    "VestingDate" = EXCLUDED."VestingDate",
    "Code" = EXCLUDED."Code",
    "OriginatingOrderID" = EXCLUDED."OriginatingOrderID",
    "OriginatingTransactionID" = EXCLUDED."OriginatingTransactionID",
    "AccruedInterest" = EXCLUDED."AccruedInterest",
    "ClientAccountID" = EXCLUDED."ClientAccountID",
    "DeliveryType" = EXCLUDED."DeliveryType",
    "CommodityType" = EXCLUDED."CommodityType",
    "Fineness" = EXCLUDED."Fineness",
    "Weight" = EXCLUDED."Weight",
    "SerialNumber" = EXCLUDED."SerialNumber"
;
