CREATE TABLE IF NOT EXISTS POSITIONS (
    CALDT DATE NOT NULL,
    FUND VARCHAR(255) NOT NULL,
    TICKER VARCHAR(255) NOT NULL,
    ASSET_CLASS VARCHAR(255),
    SHARES NUMERIC(18,6) NOT NULL,
    PRICE NUMERIC(18,6) NOT NULL,
    FX_RATE NUMERIC(18,6) NOT NULL,
    CONSTRAINT UNIQUE_POSITION UNIQUE (CALDT, FUND, TICKER)
);
